In [73]:
import pandas as pd
import numpy as np

data = pd.read_csv('지하철혼잡도_2024.csv') 
df = pd.DataFrame(data)

df.head() #데이터 확인

,연번,요일구분,호선,역번호,출발역,상하구분,5시30분,6시00분,6시30분,7시00분,...,20시00분,20시30분,21시00분,21시30분,22시00분,22시30분,23시00분,23시30분,00시00분,00시30분
0,1,평일,1,150,서울역,상선,8.2,18.9,19.8,35.7,...,19.4,18.6,18.4,15.0,17.4,18.9,15.2,13.1,7.3,1.1
1,2,평일,1,150,서울역,하선,11.1,10.7,15.7,23.5,...,39.6,37.0,42.5,36.5,41.0,29.1,18.4,16.2,5.5,0.0
2,3,평일,1,151,시청,상선,8.0,13.3,16.9,29.2,...,23.3,22.5,23.1,18.5,21.6,21.6,19.5,14.4,7.7,1.6
3,4,평일,1,151,시청,하선,9.1,9.9,17.7,22.7,...,34.1,33.6,39.1,30.2,35.1,24.5,15.8,14.1,4.1,0.4
4,5,평일,1,152,종각,상선,7.8,11.7,10.6,19.5,...,31.8,29.5,32.5,24.8,28.2,28.4,26.7,17.0,8.6,1.5

In [74]:
# 출근시간대, 퇴근시간대
columns = [
    '요일구분', '호선', '출발역', '상하구분',
    '7시00분', '7시30분', '8시00분', '8시30분', '9시00분',
    '17시00분', '17시30분', '18시00분', '18시30분', '19시00분'
]

# 데이터프레임에서 필요한 컬럼만 필터링
df = df[columns]

print(df)

     요일구분  호선  출발역 상하구분  7시00분  7시30분  8시00분  8시30분  9시00분  17시00분  17시30분  \
0      평일   1  서울역   상선   35.7   65.0   72.8   87.3   67.1    25.6    36.9
1      평일   1  서울역   하선   23.5   37.3   39.1   23.1   28.2    66.0    74.6
2      평일   1   시청   상선   29.2   48.3   60.3   58.3   52.7    29.3    41.8
3      평일   1   시청   하선   22.7   37.5   36.2   26.9   30.6    61.6    66.1
4      평일   1   종각   상선   19.5   30.0   36.8   31.3   33.4    37.2    45.2
...   ...  ..  ...  ...    ...    ...    ...    ...    ...     ...     ...
1636  일요일   8   수진   하선    3.4    4.0    6.0    7.8   12.0     7.1     6.9
1637  일요일   8   모란   상선    2.0    2.1    2.5    3.4    4.8    12.2    10.7
1638  일요일   8   모란   하선    0.0    0.0    0.0    0.0    0.0     0.0     0.0
1639  일요일   8  남위례   상선    9.5   11.7   19.6   21.8   26.7    19.1    17.5
1640  일요일   8  남위례   하선    3.7    4.6    5.1    6.1    9.7    24.7    22.1

      18시00분  18시30분  19시00분
0       49.6    39.3    30.0
1      110.4    82.2    49.1
2       69.1    49.1    33.6
3      108.8    75.6    43.5
4       89.3    63.4    41.8
...      ...     ...     ...
1636     6.3     4.9     3.6
1637    12.2    10.5     8.8
1638     0.0     0.0     0.0
1639    15.5    14.3    11.9
1640    23.2    23.6    21.3

[1641 rows x 14 columns]

In [75]:
# 요일 구분 == 평일

filtered_df = df[df['요일구분'] == '평일']

print(filtered_df)

    요일구분  호선  출발역 상하구분  7시00분  7시30분  8시00분  8시30분  9시00분  17시00분  17시30분  \
0     평일   1  서울역   상선   35.7   65.0   72.8   87.3   67.1    25.6    36.9
1     평일   1  서울역   하선   23.5   37.3   39.1   23.1   28.2    66.0    74.6
2     평일   1   시청   상선   29.2   48.3   60.3   58.3   52.7    29.3    41.8
3     평일   1   시청   하선   22.7   37.5   36.2   26.9   30.6    61.6    66.1
4     평일   1   종각   상선   19.5   30.0   36.8   31.3   33.4    37.2    45.2
..   ...  ..  ...  ...    ...    ...    ...    ...    ...     ...     ...
542   평일   8   수진   하선   19.0   21.6   23.8   17.0   12.0    12.6    10.8
543   평일   8   모란   상선    2.3    4.0    8.2   10.2    8.0    12.6    10.5
544   평일   8   모란   하선    0.0    0.0    0.0    0.0    0.0     0.0     0.0
545   평일   8  남위례   상선   45.2   64.7   79.6   76.2   62.0    36.2    24.6
546   평일   8  남위례   하선   15.1   17.8   25.8   16.7   22.3    37.4    49.4

     18시00분  18시30분  19시00분
0      49.6    39.3    30.0
1     110.4    82.2    49.1
2      69.1    49.1    33.6
3     108.8    75.6    43.5
4      89.3    63.4    41.8
..      ...     ...     ...
542    12.2     5.3     4.6
543    16.8    16.1    13.5
544     0.0     0.0     0.0
545    32.4    23.4    16.0
546    60.0    54.1    48.6

[547 rows x 14 columns]

In [76]:
# 출근시간 데이터 생성: 출근시간대 혼잡도의 평균
morning = ['7시00분', '7시30분', '8시00분', '8시30분', '9시00분']
df['출근시간_혼잡도'] = df[morning].mean(axis=1)

df.drop(columns=morning, inplace=True)

# # 결과 출력
print(df)

     요일구분  호선  출발역 상하구분  17시00분  17시30분  18시00분  18시30분  19시00분  출근시간_혼잡도
0      평일   1  서울역   상선    25.6    36.9    49.6    39.3    30.0     65.58
1      평일   1  서울역   하선    66.0    74.6   110.4    82.2    49.1     30.24
2      평일   1   시청   상선    29.3    41.8    69.1    49.1    33.6     49.76
3      평일   1   시청   하선    61.6    66.1   108.8    75.6    43.5     30.78
4      평일   1   종각   상선    37.2    45.2    89.3    63.4    41.8     30.20
...   ...  ..  ...  ...     ...     ...     ...     ...     ...       ...
1636  일요일   8   수진   하선     7.1     6.9     6.3     4.9     3.6      6.64
1637  일요일   8   모란   상선    12.2    10.7    12.2    10.5     8.8      2.96
1638  일요일   8   모란   하선     0.0     0.0     0.0     0.0     0.0      0.00
1639  일요일   8  남위례   상선    19.1    17.5    15.5    14.3    11.9     17.86
1640  일요일   8  남위례   하선    24.7    22.1    23.2    23.6    21.3      5.84

[1641 rows x 10 columns]

In [77]:
# 퇴근시간 데이터 생성: 퇴근시간대 혼잡도의 평균
evening = ['17시00분',  '17시30분',  '18시00분',  '18시30분',  '19시00분']
df['퇴근시간_혼잡도'] = df[evening].mean(axis=1)

df.drop(columns=evening, inplace=True)

# # 결과 출력
print(df)

     요일구분  호선  출발역 상하구분  출근시간_혼잡도  퇴근시간_혼잡도
0      평일   1  서울역   상선     65.58     36.28
1      평일   1  서울역   하선     30.24     76.46
2      평일   1   시청   상선     49.76     44.58
3      평일   1   시청   하선     30.78     71.12
4      평일   1   종각   상선     30.20     55.38
...   ...  ..  ...  ...       ...       ...
1636  일요일   8   수진   하선      6.64      5.76
1637  일요일   8   모란   상선      2.96     10.88
1638  일요일   8   모란   하선      0.00      0.00
1639  일요일   8  남위례   상선     17.86     15.66
1640  일요일   8  남위례   하선      5.84     22.98

[1641 rows x 6 columns]

In [83]:
p = df[df['출발역']== '군자']

print(p)

     요일구분  호선 출발역 상하구분  출근시간_혼잡도  퇴근시간_혼잡도
310    평일   5  군자   상선     78.30     38.78
311    평일   5  군자   하선     52.50     88.40
459    평일   7  군자   상선     29.26    113.06
460    평일   7  군자   하선    133.66     37.08
857   토요일   5  군자   상선     32.84     37.84
858   토요일   5  군자   하선     30.36     61.62
1006  토요일   7  군자   상선     23.26     73.40
1007  토요일   7  군자   하선     67.28     44.86
1404  일요일   5  군자   상선     21.18     25.36
1405  일요일   5  군자   하선     19.20     43.98
1553  일요일   7  군자   상선     18.12     57.22
1554  일요일   7  군자   하선     38.10     36.26

In [78]:
# 출근시간 혼잡한 역 상위 5개

top5_morning = df.nlargest(5, '출근시간_혼잡도')

print(top5_morning)

    요일구분  호선     출발역 상하구분  출근시간_혼잡도  퇴근시간_혼잡도
460   평일   7      군자   하선    133.66     37.08
458   평일   7      중곡   하선    132.00     36.64
462   평일   7  어린이대공원   하선    131.36     42.94
71    평일   2      사당   외선    129.30     42.26
456   평일   7     용마산   하선    126.68     34.02

In [79]:
# 출근시간 파일 생성 및 저장
top5_morning.drop(columns='퇴근시간_혼잡도', inplace=True)

# '출근시간_혼잡도': 소수점 둘째 자리로 포맷
top5_morning['출근시간_혼잡도'] = top5_morning['출근시간_혼잡도'].map('{:.2f}'.format)
print(top5_morning)

# CSV 파일로 저장
top5_morning.to_csv('top5_morning.csv', index=False)

    요일구분  호선     출발역 상하구분 출근시간_혼잡도
460   평일   7      군자   하선   133.66
458   평일   7      중곡   하선   132.00
462   평일   7  어린이대공원   하선   131.36
71    평일   2      사당   외선   129.30
456   평일   7     용마산   하선   126.68

In [80]:
# 퇴근시간 혼잡한 역 TOP 5
top5_evening = df.nlargest(5, '퇴근시간_혼잡도')

print(top5_evening)

    요일구분  호선      출발역 상하구분  출근시간_혼잡도  퇴근시간_혼잡도
68    평일   2       방배   내선     28.98    127.00
66    평일   2       서초   내선     30.18    123.34
64    평일   2       교대   내선     35.32    118.78
214   평일   4      동대문   상선     26.70    118.66
502   평일   7  가산디지털단지   하선     24.98    116.86

In [81]:
# 퇴근시간 파일 생성 및 저장
top5_evening.drop(columns='출근시간_혼잡도', inplace=True)

# '퇴근시간_혼잡도': 소수점 둘째 자리로 포맷
top5_evening['퇴근시간_혼잡도'] = top5_evening['퇴근시간_혼잡도'].map('{:.2f}'.format)
print(top5_evening)

# CSV 파일로 저장
top5_evening.to_csv('top5_evening.csv', index=False)

    요일구분  호선      출발역 상하구분 퇴근시간_혼잡도
68    평일   2       방배   내선   127.00
66    평일   2       서초   내선   123.34
64    평일   2       교대   내선   118.78
214   평일   4      동대문   상선   118.66
502   평일   7  가산디지털단지   하선   116.86